- QRCoder/QRCoder.NET40.csproj
- QRCoder/QRCoder.csproj
- QRCoder/XamlQRCode.cs
- QRCoderConsole/Program.cs
- QRCoderConsole/QRCoderConsole.csproj
- QRCoderConsole/SupportedImageFormat.cs
This PR adds support for XAML to make QRCoder directly usable in WPF projects.
Furthermore, it extends QRCoderConsole utility with the ability to output XAML files.
The code has been ported from https://github.com/Amebis/eduVPN/blob/master/eduVPN.Client/QRCoder/XamlQRCode.cs under originating author permission.
Example use-case:
```C#
public class TOTPQRConverter : IMultiValueConverter
{
public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
{
try
{
var secret = values[0] as string;
var hostname = values[1] as string;
var displayname = values[2] as string;
var otp_uri = string.Format("otpauth://totp/{1}?secret={0}&issuer={2}",
secret,
hostname,
HttpUtility.UrlEncode(displayname));
var qr_generator = new QRCodeGenerator();
var qr_code_data = …
```
> Support for Xaml

- QRCoder/SvgQRCode.cs
**Test plan**
Tested with the bug producing code as explained in #116
Fixes #116
> Fix svg rendering

- QRCoder/PayloadGenerator.cs
- QRCoder/QRCodeGenerator.cs
This PR implements the following **features**:
> added SlovenianUpnQr payload generator, manual QR version and ECI mode

- QRCoder/QRCodeGenerator.cs
This change doesn't modify the galoisField values as the previous version worked just fine in regard to the data generated. It was just doing an unnecessary Pow() calculation that was meaningless after the value of "i" was greater than 7.
**Test plan**
Demonstrate that your code is solid. If possible add a short test case/test steps.
Fixes #
> CreateAntilogTable doing unnecessary Pow calculations

- QRCoder/XamlQRCode.cs
**Summary**
Refactors the GetGraphic loop for Xaml QR Code to avoid a System.OutOfRange Exception, especially when dealing with `unitsPerModule` values that are doubles with repeating decimal places.
An example of this found in the original bug issue was that the size limit was `200`, but the unlimited precision of the double `yi` allowed it to reach a value of `199.99999992` (rough estimate) and so the loop did not terminate as expected.
This refactor instead loops on the data of the QR code (always an `int`) while adding to the pixel values, a reverse of the original structure. This avoids the System.OutOfRange exception when accessing the QR code data.
This PR fixes the following **bugs**:
Fixes OutOfRangeException encountered in #145 …
> fixed issue #145 with OutOfRange Exception generating Xaml QR Code images

- QRCoder/BitmapByteQRCode.cs
- QRCoderProject.NET40.sln
**Summary**
Small change to `HexColorToByteArray` method in `BitMapQRCode.cs` which fixes parsing of RGB values from hex strings.
Previously this was done backwards, so the value would be read as BGR instead of RGB.
In #139, this manifested noticeably where `#FF0000` would be output to an image as `#0000FF`
This PR fixes the following **bugs**:
**Test plan**
Tested with case identified in #139, generating an image with color: `#FF0000` has expected color on output: ([imgur link](https://imgur.com/a/Twx0Iom))
`closes #139`
> Issue 139 rgb color generation

- QRCoder/PayloadGenerator.cs
**Summary**
Adds `stateRegion` as an attribute to `ContactData.cs` for use in generating meCard/vCard payloads that include the State or Region values for Address.
Additionally, reorganized `houseNumber` and `street` to more closely follow the `<houseNumber> <street>` convention for addresses.
Adds State or Region as an option when generating a Payload for vCard/meCard
Fixes issue with House Number and Street being backwards in the payload
**Test plan**
*vCard*
Using this code to generate a payload
```csharp
var vCard = new ContactData(ContactData.ContactOutputType.VCard3, "John", "Smith", "Johnny", "1234567890", 
"1234567890", "1234567890", "johnny497@email.com", DateTime.Now, …
```
> #146 added stateRegion to ContactData as an option for Addresses

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
This PR gives creates a new overload to the WhatsApp payload by giving the user the ability to add contact/phone number to WhatsApp Payload. This is can be achieved since WhatsApp is allowing passing the contact/phone number in the following format
`$"whatsapp://send/?phone={number}&text={message}"`
This PR fixes/implements the following **features**:
Just adding gives the user a new feature to send the WhatsApp message directly to the desired contact.
**Test plan**
Demonstrate that your code is solid. If possible add a short test case/test steps.
UnitTests:
- [ whatsapp_generator_can_generate_payload_simple] still working.
- [ whatsapp_should_add_unused_params] new unit test method to test if the phone number is missing. 
**Closing …
> Add contact/phone number to WhatsApp Payload

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
This is PR to fix the issue in implementing the SwissQR since the current implementation is not fulfilling the the SwissQR requirements when it comes to amount field. Check page 15 in [https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf ](url)
> If the amount is included in the Swiss QR Code, then it must be printed after the currency code. A blank (space) should be used as the thousands separator and a full stop
"." as the decimal separator. The amount must always include two decimal places.
Fixing the amount field logic to make it fulfill the SwissQR requirements since a blank (space) should be used as the thousands separator so 1234567.89 should be 1 234 567.89 …
> fix-swissQR-number-issue-#96

- QRCoder/PayloadGenerator.cs
Root cause: Null was checked on phone field to add the website field to the vcard
The website field was never added to the vcard if it was of type other than MeCard and if the phone field was null.
**Test plan**
Existing test cases should pass.
Fixes #
Changed the null checking to website field for adding the website data to the vcard.
> The website field is not added to the vcard if it was of type other than MeCard

- QRCoder/QRCodeGenerator.cs
**Summary**
Adds a new method `public QRCodeData CreateQrCode(byte[] binaryData, ECCLevel eccLevel)` to encode binary data.
I need to encode binary data containing null-bytes. This is impossible with the string-based `CreateQrCode` methods, since the data would be truncated.
> Add support for binary data

- QRCoder/XamlQRCode.cs
**Summary**
This is a helper method allowing client to obtain an exact measure of module size without a need to repeat the calculation by itself.
When the client wants to draw a border around QR code or some other adornments which need to use the same size and/or spacing as the module size this commit simplifies its calculation.
> Add XamlQRCode.GetUnitsPerModule() method

- QRCoder/XamlQRCode.cs
**Test plan**
The following generated QR code has missing right and bottom parts (after the merge it works correctly):
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("TestString", errorCorrectionLevel);
XamlQRCode qrCode = new XamlQRCode(qrCodeData);
DrawingImage qrCodeAsXaml = qrCode.GetGraphic(5, false);
> XamlQRCode with drawQuietZones = false bugfix

- QRCoder/PayloadGenerator.cs
Fix concerning the issue 217
Allow + sign in company names when creating qrcode.
> Issue 217 allow + character in company name

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
**Summary**
We are using QRCoder from C++/CLI. With the conformance improvements in Visual Studio 2019 version 16.6 (see https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019#default-argument-import-in-ccli), there is now an ambiguous call error when using the QRCoder.PayloadGenerator.SwissQrCode.Contact constructor for a combined address (four strings). The reason for this is that the other public constructor (for a structured address) takes also four strings and two more strings that default to null.
I added "named constructors" (static methods returning a Contact). The existing public constructors are still there (to avoid breaking changes), but marked as obsolete/deprecated.
**Test plan**
In the second commit, I adjusted all the (now …
> Named constructors for QRCoder.PayloadGenerator.SwissQrCode.Contact

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
- readme.md
**Summary**
This pr contains new payload generators for Bitcoin Cash and Litecoin cryptocurrencies.
**Test plan**
I add more tests for this. They similar to Bitcoin payload generator tests.
**Additional information**
If this pr will be approved I also want update this [part](https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#32-bitcoin-payment-address) on wiki to add additional examples and update this paragraph.
> Add new payload generators for Bitcoin-Like cryptocurrencies

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
No ability to generate a contact card with Organization.
**Test plan**
Ran unit tests with no issues.
I've successfully generated contact cards (VCard3) with the org parameter supplied.
Fixes #274
> adding support for Org in PayloadGenerator.ContactData

- QRCoder/SvgQRCode.cs
This PR implements the following feature:
* Reduce the number of SVG rectangles by about 50%~60%
> Reduce the number of SVG rectangles

- QRCoder/PayloadGenerator.cs
This PR introduces a new parameter for the WifiPayload generator called "escapeHexStrings" with default=true. Thus is default keeps the same behaviour as before this PR and can be called "non-breaking".
If set to "false" ssid and password passed to the WifiPayload generator won't be escaped, even if they are in HEX syntax. This behaviour is non-standard (the standard defines HEX escaping), but may be necessary for Apple devices, because they seem to be unable to handle those escaped strings.
> Added new optional parameter to disable Hex-escaping

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
Added more tests and removed empty parameters.
Closes #345
> Refactored SMS, MMS & Mail generator.

- .github/workflows/wf-build-release-ci.yml
- .github/workflows/wf-build-release.yml
- .github/workflows/wf-build-test.yml
Updated build scripts In preparation for the XamlQRCode carve-out. Scripts should be updated first, so that build and test runs, when XamlQRCode is decoupled from QRCoder.
> Updated build scripts

- .github/workflows/wf-build-release-ci.yml
- .github/workflows/wf-build-release.yml
- .github/workflows/wf-build-test.yml
**Summary**
Switch from windows-latest (2019) to windows-2022 for net6.0 support
> Switch from windows-latest (2019) to windows-2022 for net6.0 support

- .github/workflows/wf-build-release-ci.yml
- .github/workflows/wf-build-release.yml
- .github/workflows/wf-build-test.yml
- QRCoderTests/ArtQRCodeRendererTests.cs
- QRCoderTests/PngByteQRCodeRendererTests.cs
- QRCoderTests/QRCodeRendererTests.cs
- readme.md
* Fixes GitHub Action workflows.
* Removes ifdef for hashes on NETFX.  Not sure why they were there, but tests fail unless they are removed, both locally and within CI.
> Fix workflows

- QRCoder/SvgQRCode.cs
- QRCoderTests/SvgQRCodeRendererTests.cs
This PR allows SVGs to be created under .NET 6 on Linux.  The majority of the code is already compatible and does not use System.Drawing.  The only code that does is the constructor for SvgLogo.  This implementation simply removes only that constructor on .NET 6 on Linux, without removing any other code, allowing:
1. SVGs without an embedded logo may be created
2. The alternate SvgLogo constructor may be used, for SVG-based logos
This does not allow users to use PNG-based logos on .NET 6+ on Linux -- a 3rd constructor could be added for that scenario, either public or protected, where the user would supply the PNG data (generated from a third-party image library, for example).  This is solved by #491 which can be merged independently.
This allows users of QRCoder on Linux to export SVG …
> Allow SVG exporting under .NET 6 on Linux

- QRCoder/SvgQRCode.cs
- QRCoderTests/SvgQRCodeRendererTests.cs
This PR fixes/implements the following bugs and features:
* Fixes a bug where extra null bytes are included with the logo embedded within a SVG
* Adds a constructor allowing for a custom PNG file data to be supplied to the logo embedded within a SVG
When using a third-party library to encode image data, or when reading PNG directly from a stream, this additional constructor allows for it to be passed directly to the created SVG file, without passing through the System.Drawing library.
Tests have been added to the codebase
> Support passing PNG data directly to SvgLogo

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
Currently, if you create an OTP with an issuer that contains a space, for example:
```cs
var oneTimePassword = new OneTimePassword {
Issuer = "Google Google",
Label = "test@google.com",
Secret = "pwq6 5q55"
};
```
and then call `ToString` on that `oneTimePassword`, that will return:
`otpauth://totp/Google Google:test@google.com?secret=pwq65q55&issuer=Google%20Google`
(note the first "Google Google" is not escaped, like the second one in the `issuer` parameter)
which then looks like this in Google Authenticator after scanning the resulting QR code:
This PR resolves this issue by correctly escaping both instances of the issuer in the URL, which then appears correctly in Google Authenticator: …
> Ensure that an OTP's issuer and label values are escaped correctly

- QRCoder/PayloadGenerator.cs
Bug #399 If BillInformation is empty, insert no linebreak
See description from bug #399 
Create SwissQRCode with:
- Trailer "EPD"
- UnstrucureMessage "Text"
- BillInformation [empty or null]
Result --> if you scan the qrCode after "EPD" does not exist a line break! ;-)
Fixes #399 and #398
> Bugfixing # 399

- QRCoder/ArtQRCode.cs
修正在绘制自定义finderPatternImage时，同时绘制QuietZones会出现位置异常的BUG
> fix:修正在绘制自定义finderPatternImage时，同时绘制QuietZones会出现位置异常的BUG

- QRCoder/ASCIIQRCode.cs
- QRCoderTests/AsciiQRCodeRendererTests.cs
Implementation of a new method that generates a small qrcode.
Inspired by the repository https://github.com/gtanner/qrcode-terminal.
Implemented a basic test function (can_render_small_ascii_qrcode).
Fixes #379
> ASCIQRCode Small

- QRCoder/PayloadGenerator.cs
- QRCoderTests/PayloadGeneratorTests.cs
Inspired by issue #458 and the discussion there, this PR extends the CalendarEvent payload generator with a UTC DateTime functionality.
This PR fixes the following **problems**:
- If plain DateTime objects (with DateTime.Kind.Unspecified) are passed to the payload generator nothing change, to avoid breaking changes
- If DateTime objects with DateTime.Kind.Utc are handed over, the payload generator will respect the UTC and save the dates as "UTC" in the iCal calendar event
- Another constructor overload is added that accepts DateTimeOffset instead of DateTime objects. Those will be converted to DateTime objects with Kind.Utc internally by use of the offset defined in the DateTimeOffset objects.
Test cases were added to the PayloadGeneratorTests.cs
Fixes #458
> Added support for UTC and DateTimeOffsets in VEVENT generator
